name: Docker Github Actions 

on: 
  pull_request: 
    types: [closed]
    branches: 
      - main 


jobs: 
  docker:  
    environment: docker
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest 
    steps: 
     
      - name: Checkout Repository 
        uses: actions/checkout@v4
      - name: Login to Dockerhub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build Image 
        run: docker build -t mynginx:test . 
      # test Image 
      - name: Test Docker Image 
        run: | 
          docker run -d -p 8080:80 --name test-nginx mynginx:test 
          sleep 10 # একটু সময় বাড়িয়ে দিন যেন কন্টেইনার পুরোপুরি রেডি হয়
          
      - name: Health check and Test
        run: |
          curl -f http://localhost:8080 
          # টেক্সট চেক করা
          curl http://localhost:8080 | grep "This is a docker lab using nginx"

      - name: Cleanup
        if: always()
        run: |
          docker stop test-nginx
          docker rm test-nginx
      # push Image  
      - name: Push To Dockerhub 
        run: | 
          docker tag mynginx:test ${{ secrets.DOCKER_USERNAME }}/mynginx:latest 
          docker push ${{ secrets.DOCKER_USERNAME }}/mynginx:latest 





